### ISSUE TITLE
一部のメソッドにロガーが未実装

### ISSUE THREAD

**Issue by Keigo01** [kusumotolab/kGenProg#160]
富田君の実装開始以降に実装されたメソッドについてロガーが実装されていない．
ただ，今後ロガーの実装を別で行ったとしても，いたちごっこになってしまうため，
ロガーに関して同意を取り，今後は各自メソッド実装の際に自分でロガーを書くのが良いかもしれません．

**Comment by YoshikiHigo** [comment]
すでに他のISSUEでカバーされている．
#335 #407 で解決済み．
