### ISSUE TITLE
内部開発者向け共有情報のドキュメント化

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#162]
### 問題は？
共有すべき情報がwikiやPR等に散らばっており，どこを見ればよいのか不明．
各情報を抜き出して，一元管理すべき．

### 共有すべき情報は？
- ロガーの方針 #113 
- 開発環境整備
  - コーディングルール系
- ...
#25
ま）あとでやる

**Comment by hnymA** [comment]
kGPチームに新規参入して思ったことを書いておきます．
これから情報をドキュメント化する上でも参考になるかと思います．

## コーディングスタイル
- 改行はCRLF？LF？
- インデントは？
など
→ Google Coding Styleに準拠する（あとで知った）：#15

## コミット
- ブランチどうする？
→ [wikiの「開発フロー」](https://github.com/kusumotolab/kGenProg/wiki/%E9%96%8B%E7%99%BA%E3%83%95%E3%83%AD%E3%83%BC)に書いてある
- コミットメッセージは日本語？英語？
→ **未だによく知らない**

## プルリク
- タイトルは？
→ [wikiの「開発フロー」](https://github.com/kusumotolab/kGenProg/wiki/%E9%96%8B%E7%99%BA%E3%83%95%E3%83%AD%E3%83%BC)に書いてある
- レビュワーの基準は？
→ **未だによく知らない**

## その他
- 全体的な構造が分からない
→ 先輩が貼ってくださった：https://github.com/kusumotolab/kGenProg/issues/162#issuecomment-441874815
- GAの用語が分からない
→ [wikiの「GAのデータ構造」](https://github.com/kusumotolab/kGenProg/wiki/GA%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E6%A7%8B%E9%80%A0)に書いてある
- ロガーについて
  - `public`なメソッドを実装したり修正するときはログを差し込む必要がある（あとで知った）
→#113 や #160

**Comment by a-tanikd** [comment]
> プルリク
> タイトルは？
> → wikiの「開発フロー」に書いてある

これも Obsolete
PR タイトルには対応する issue 番号は書かずに，本文で `resolve #xx`，`close #xx` 等のように記述する．

**Comment by h-matsuo** [comment]
最近読んだ OSS のドキュメントの中で「分かりやすい」と思ったものを例に挙げておきます：

### [Ansible module development: getting started](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html)

- ドキュメント専用の Web ページを持っている例
- 一番最初に何のコマンドを実行すべきか，テストはどう実行できるのかなど，開発に必要な情報が詳しく載っています

### [circleci-cli](https://github.com/CircleCI-Public/circleci-cli/blob/master/HACKING.md)

- GitHub 内に Markdown 形式で書いている例
    - `CONTRIBUTING.md` という名前で書いてあることが多いです
- こちらも同様，環境設定などがコンパクトにまとまっています

**Comment by YoshikiHigo** [comment]
どこに書くか？　→ とりあえずMDに書く．doc/CONTRIBUTING.mdにする．
- 環境セットアップ：依存環境，git cloneした直後のコマンド(git-submodule, gradle dependencies)，フォーマッタの導入，
- 実装：改行コード指定
- フロー：
- 詳細な内部構造：パッケージの説明，用語集．

上3つは @shinsuke-mat ，一番下はおいおい．

**Comment by hnymA** [comment]
- CONTRIBUTING.md
- javadoc
- kGP overview
  - 用語
  - ストラテジ（全体像．詳細はjavadocへ）
