### ISSUE TITLE
進化の過程を確認できない

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#238]
実装・研究の両面でとても重要なISSUE．

### 問題は？
現在，進化の結果（diff）のみが出力されており，その過程を確認する方法が存在しない．
よって，以下のような分析が全く出来ない．

- どのような操作が適用されているか．
- 空間を効率的に探索できているか．
- なぜバグ修正に失敗したか．

### 対処は？
課題は大きく分けて2つ．
そろそろよく考えないと実装が苦しい．
- A. （成功だけでなく失敗も含めて）進化の過程をどう保持するか．
- B. 保持した進化の過程をどう見せるか．

**Comment by YoshikiHigo** [comment]
refer #349
