### ISSUE TITLE
main起動時のconfigの検討

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#26]
main起動の方法が引数で渡すだけでなく，configでどかんと渡したい．

    // 引数で実行
    $ main -s example01/src/main/java/ -t example01/src/test/java ...
    // configで実行
    $ main --config kgenprog.conf

configの中身や書式は要検討．

**Comment by a-tanikd** [comment]
toml のパースには [TheElectronWill/Night-Config](https://github.com/TheElectronWill/Night-Config) が使えそう
