### ISSUE TITLE
exampleフォルダは設置場所が良くない

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/kGenProg#278]
testresoucesに変更することになった？testresources? test-resources?

**Comment by shinsuke-mat** [comment]
exampleをsrc/test/resources直下に配置してみた．
その後 `gradle eclipse` でeclipseプロジェクトを再構成した．

問題：eclipseがsrc/test/resources配下をjavaファイルとして認識してしまうので，
コンパイルエラーだらけで地獄．

![image](https://user-images.githubusercontent.com/5342911/46052884-45252300-c17b-11e8-8c05-4ef10c0ab864.png)

これどうすんねん．

**Comment by shinsuke-mat** [comment]
@a-tanikd @a3636tako @Keigo01 と相談．

現状の `example` が `src/test/resources` にあるべき，という理屈は納得．
しかし， `src/test/resources` に移動するメリットが見当たらない．
よって `example` は現状のままにする．

また，#320 の修正（実プロジェクトのgit submodule）の結果，`example` フォルダの構成はこうなる．

```
example/
  - BuildFailure01/
  - BuildSuccess01/
  - BuildSuccess02/
  - ...
  - CloseToZero01/
  - ...
  - real-bugs/  # ここがsubmodule（実プロジェクト系リソース）
     - Math02/
     - Math05/
     - ...
```

**Comment by shinsuke-mat** [comment]
上記議論により，このISSUEは対策せずそのままexampleフォルダに設置しておくことに．
よってclose．
