### ISSUE TITLE
Cluster-based APR

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#282]
複数のdockerを用意してVariant生成をdockerに依頼する．
dockerは結果を返してVariantStoreに保持する．

並列処理+APR

**Comment by a3636tako** [comment]
# どこを分散させるか

ビルド＆テストを分散させたい (一番時間のかかる処理)

第1段階

メインマシン <=> ビルド＆テストマシン

第2段階

メインマシン <=> [ビルド&テストマシン]*n

# マシン間の通信をどうするか

## TCP を使って独自実装
TCPソケット通信を直接記述する

pros: KGPに合わせてカスタマイズしやすい
cons: コネクション制御、シリアライズ、エラー制御などをすべて自分で行わなければならない

## Java RMI
Remote Method Invocationの略。Javaプログラム中からはメソッドを呼び出すだけでリモートで処理を実行できる。

pros: Javaプログラムを書くだけなので実装しやすい
cons: 古い情報が多く、実際に使われているか不明。速度が遅いという情報もあり。

## gRPC
Googleが開発しているRPC (Remote Procedure Call)

pros: 最近さかんに開発されている。(HTTPに比べて)高速
cons: Javaに特化したものではないので、大げさ？

## HadoopやSparkの通信部分
HadoopやSparkでは独自のRPC実装を用いている。

pros: 高速らしい 
cons: その部分だけを使えるのか、使いやすいのかわからない

## Akka
並行・分散処理のためのフレームワーク。アクターモデルというものに従うらしい

pros: ノードの管理、ロードバランス等をフレームワーク側でやってくれる
cons: フレームワークなのでKGPにうまく取り込めるか不明

**Comment by a3636tako** [comment]
新しくリポジトリを作った
https://github.com/kusumotolab/clustered-kGenProg
