### ISSUE TITLE
NullObjectがシングルトンのせいでデバッグが難しい

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#284]
NullObjectにより異常系であってもそれを匂わせずにナチュラルに実装可能．
このナチュラルさのせいでデバッグが難しくなっている．

ビルド失敗やテスト失敗時にNullObjを返すのは良いけど，
きちんとLoggerにも書き込まないといけない．

**Comment by mtj0928** [comment]
NullObjectを作成した各々が修正をする

**Comment by mtj0928** [comment]
### 修正内容
- シングルトンをやめる
- 失敗理由をオブジェクトに保持させる
- debug ログを入れる

**Comment by RyokoIzuta** [comment]
この問題，私の研究でも問題になったので対応していただきたいです．
具体的には，ビルド失敗個体のビルドエラーログが欲しいのに，見れませんでした．

**Comment by YoshikiHigo** [comment]
お，この問題今日のミーティングで議論しましょう．
