### ISSUE TITLE
Variantからビルドやテスト結果に関する情報を取りたい

### ISSUE THREAD

**Issue by a3636tako** [kusumotolab/kGenProg#295]
ビルドが成功したか、失敗したか、テストが成功したか、失敗したかなどの情報をVariantから取得したい。

getStatusのようなメソッドを作る？

**Comment by mtj0928** [comment]
成功系は取れるはず。
失敗系は、 #284 の修正でなおす。

**Comment by YoshikiHigo** [comment]
#428  で解決済み．
