### ISSUE TITLE
CUI引数の妥当性チェックがない

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#304]
https://github.com/kusumotolab/kGenProg/blob/53e04394283d1f859f4c4ff269a75b1193d0d13b/src/main/java/jp/kusumotolab/kgenprog/Configuration.java#L168-L174

ここでチェックすべき．
- カレントディレクトリと対象プロジェクトのディレクトリがずれている警告
- Pathがない
- ...

**Comment by mtj0928** [comment]
Pathがずれている場合のチェックのみ完了
それ以外の妥当性のチェックはできていない

**Comment by YoshikiHigo** [comment]
depends on #450

**Comment by a-tanikd** [comment]
この issue では，Path の存在確認のみを行う．
他の妥当性確認は #461 で行う．
