### ISSUE TITLE
FileUtilsは性能が良くない

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/kGenProg#305]
kGenProgでは指定したディレクトリ以下のファイルの収集にcommons-ioのFileUtilsを使っているが，速度的には優れていない模様．
https://github.com/brettryan/io-recurse-tests#io-recurse-tests

**Comment by YoshikiHigo** [comment]
ちなみに，僕が作っている他のプロジェクト（大量のファイルIOを含む）で，commons-ioのFileUtilsをnio.Files#findに変えたところ，9分かかっていた処理が7分になった．

**Comment by mtj0928** [comment]
kGenPrpgにioがあまりないので、効果はなさそうだが依存は減りそう
おいおいやっていく
`Files#walk` を使う
