### ISSUE TITLE
ビルドのインメモリ化

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#306]
see #33 

KGPの特徴の一つとして「あらゆる作業をインメモリ化することで高速化する」という点を売りたい．
テストはインメモリ化できている．
あとはビルドのインメモリ化．

現状，「メモリ上のjavaファイル→メモリ上のclassファイルの生成」まではOK．

**Comment by shinsuke-mat** [comment]
ビルドの際のクラスパスのインメモリ化がむずかしい．

まず，初回ビルドは全javaファイルを読み込んでビルド，結果をメモリに乗せる（ここはOK）．
2回目ビルドでは，（メモリ上の，かつAPRで変更された）astをビルドする．
この時，そのastが依存している別クラスをクラスパスに通さないといけない．
この別クラスとは，初回ビルドで生成したメモリ上のバイトコードのこと．

現状，クラスパスの指定はビルド時のオプションで指定している．
具体的には，`-classpath` 引数を使って普通のFSへのパスを指定している．
```
    compilationOptions.add("-classpath");
    compilationOptions.add("bin");
```
ここをどうメモリ化するのか？

**Comment by shinsuke-mat** [comment]
# 案1：クラスローダに依存バイナリを渡してみる．
### 方法
まず，メモリ上のバイナリを読み込むクラスローダ（MemoryClassLoader）を使って，
依存バイナリをクラスロードしておく．
そのクラスローダで `JavaCompiler` インスタンスをロードして，
クラスローダの委譲処理の過程で依存バイナリが読み込まれることを期待する．

### 結論
この案は不可能．
ビルド時にはクラスローダのバイナリを読むわけではなさそう．

**Comment by shinsuke-mat** [comment]
## 案2：メモリ上のFSを作ってJavaCompilerにわたす
### 方法
極めて合理的なやり方．

1. まず，メモリ上の（論理的な）FSを作る．
2. そこにコンパイルしたバイナリを乗せる．
3. そのFSをJavaCompilerにわたす．

### 実装
123を実装するとこうなる．完璧に見える．
```java
    // 標準FSのバイナリを一旦読み込んでおく（コンパイル後のバイナリを想定）
    Path fooBin = Paths.get("example/BuildSuccess09/bin/example/Foo.class");
    byte[] fooBytes = Files.readAllBytes(fooBin);

    // jimfsに上記バイナリを設置
    final FileSystem fs = Jimfs.newFileSystem(Configuration.unix()); // ★1
    Path fooBinInMemoryPath = fs.getPath("example/Foo.class");
    Files.createDirectory(fs.getPath("example"));
    Files.write(fooBinInMemoryPath, fooBytes); // ★2

    // JavaCompilerにクラスパスとして上記メモリ上バイナリを渡す
    final File file = fooBinInMemoryPath.toFile(); // ★ ここでUnsupportedOperationException
    List<File> files = Arrays.asList(file);
    standardFileManager.setLocation(StandardLocation.CLASS_PATH, files); // ★3
```

### 実装の詳細
1. → Google製の[jimfs](https://github.com/google/jimfs)で簡単にできる．
あたかも普通のFSのようなディレクトリ構造を使ってファイルをメモリ上に設置できる．
```java
    final FileSystem fs = Jimfs.newFileSystem(Configuration.unix()); // ★1
```

2. → 余裕
```java
    Files.write(fooBinInMemoryPath, fooBytes); // ★2
```

3. → `-classpath` オプションではなくファイルマネージャにわたすことで可能っぽい．
https://stackoverflow.com/a/8455259
```java
    standardFileManager.setLocation(StandardLocation.CLASS_PATH, files); // ★3
```

### 問題
jimfsが `java.nio2 (Path)` 前提でらう一方で，JavaCompilerが `java.io (File)` を前提に動いている．
jimfsは `java.io` への後方互換を持っていない．
よって，`toFile()`を呼び出すと `UnsupportedOperationException`．
```java
    final File file = fooBinInMemoryPath.toFile(); // ★ ここでUnsupportedOperationException
```

**Comment by shinsuke-mat** [comment]
### 問題（つづき）
https://stackoverflow.com/questions/31183269/jimfs-how-to-get-file-from-path
やはり `java.io.File` の仕組みが古く理屈の上で不可能っぽい．
`java.nio.Path` は標準以外のFSでも動くような，FSの切り離しが可能であるのに対し，
`java.io.File` は標準FSでしか動かないっぽい．

**Comment by shinsuke-mat** [comment]
### つづき
別のメモリFSでも同じこと書いてあるわ
https://github.com/marschall/memoryfilesystem#usage
> Don't use File, FileInputStream, FileOutputStream, RandomAccessFile and Path#toFile(). These classes are hard wired to the default file system.

**Comment by shinsuke-mat** [comment]
java10ならJavaCompilerが `java.nio.Path` を使って処理できるらっぽい．

https://docs.oracle.com/javase/jp/10/docs/api/javax/tools/StandardJavaFileManager.html#setLocationFromPaths(javax.tools.JavaFileManager.Location,java.util.Collection)

**Comment by shinsuke-mat** [comment]
## 案3：CompilationTask生成時のFSを真面目に拡張する
もうこれしかない．
最も現実的かつ真面目な方法．

[`javax.tools.JavaCompiler#getTask`](https://docs.oracle.com/javase/jp/8/docs/api/javax/tools/JavaCompiler.html#getTask-java.io.Writer-javax.tools.JavaFileManager-javax.tools.DiagnosticListener-java.lang.Iterable-java.lang.Iterable-java.lang.Iterable-)がうまく設計されていて，独自ファイルマネージャを指定できる．

案2でもグダグダ書いたように，ファイルとFSの関係はこうなる．
```java

// Java7まではこう，標準FSと切り離せないのでメモリ化不可能
java.io.File
 --> OS標準のFS

// ★javax.tools周り，IF結合なので切り離し可能
javax.tools.JavaFileObject (IF)
 --> javax.tools.JavaFileManager (IF) 

// ちなみにJava8，ただしjavax.tools.JavaCompilerがPath非対応なので不可能
java.nio.Path
 ---> 任意のFS
```

★の部分の2つのIFをうまく実装すればインメモリ化は理屈の上ではできるはず．

**Comment by shinsuke-mat** [comment]
既存の `JavaMemoryObject` と `InMemoryClassManager` を拡張することでできた．
GOD

**Comment by mtj0928** [comment]
@shinsuke-mat が作業中。
大枠の機能は完成しているが、いくつかバグが残っている。

**Comment by shinsuke-mat** [comment]
備忘録：差分ビルド方法の議論1
![a](https://user-images.githubusercontent.com/5342911/47899823-232b6880-debe-11e8-8b73-cab266814b83.jpg)

**Comment by shinsuke-mat** [comment]
備忘録：差分ビルド方法の議論2
![b](https://user-images.githubusercontent.com/5342911/47899835-2d4d6700-debe-11e8-919a-411b75f2584c.jpg)

**Comment by shinsuke-mat** [comment]
備忘録：差分ビルド方法の議論3
![c](https://user-images.githubusercontent.com/5342911/47899843-34747500-debe-11e8-8587-6b0f4e41cdf8.jpg)
