### ISSUE TITLE
ルーレットが落ちる

### ISSUE THREAD

**Issue by mtj0928** [kusumotolab/kGenProg#315]
`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0`で落ちる

https://circleci.com/gh/kusumotolab/kGenProg/604?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by shinsuke-mat** [comment]
#322 はCI上で本ISSUEが発生したりしなかったりという問題なので，ひとまず置いとく．

本ISSUE自体はやはり潜在バグとして潜んでいそう．
実アプリ（Math85）を対象とした時に必ず再現する．
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
```

ただ，（乱数によるが）何世代か後に出てくるのでかなりデバッグが難しい．

**Comment by shinsuke-mat** [comment]
なるほど，テストのバグ．
P1は解決．
```java
public class KGenProgMainTest {
  private static KGenProgMain createMain(...) {
    ...
    final Random random = new Random();  // あかんで
    final Random random = new Random(0); // こうやで

**Comment by shinsuke-mat** [comment]
P2もパッチはできた．

```diff
public class RandomMutation extends Mutation {
  public List<Variant> exec(final VariantStore variantStore) {
    ..
    for (final Variant variant : variantStore.getCurrentVariants()) {
      ..
+      if(suspiciousnesses.isEmpty()) {
+        continue;
+      }
```

ビルド失敗の時に `suspiciousnessが空になる模様．
全てのビルド失敗がここを通過するわけではなさそう．

@mtj0928 
ともあれ上記は一時パッチのようなものなので，もっと良い方法ないか考えて．

**Comment by shinsuke-mat** [comment]
ちなみにCloseToZero02等でも再現する．
ただ3世代目当たりで発生したりするので，
- 乱数を適当に変えて早い段階で出現するようにする
- printデバッグ

等の工夫が必要だと思う．

**Comment by a3636tako** [comment]
Variant.isCompleted == true の場合でもsuspiciousnessが空になるので例外が発生しました。
成功Variantが除去されていないのが問題のようです
