### ISSUE TITLE
CI上で再現性のないバグが発生する

### ISSUE THREAD

**Issue by Keigo01** [kusumotolab/kGenProg#322]
depends on #315
テストが稀に失敗する．
5299444228548e8448ec26078295a16084134086 のCIによるテストで発生していたが，リビルドをかけると再現しなかった．
その後同一バージョンで10回CIを走らせたが，バグは再現しなかった．
[エラー発生時のCI](https://circleci.com/gh/kusumotolab/kGenProg/604?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by shinsuke-mat** [comment]
https://circleci.com/gh/kusumotolab/kGenProg/642
別PRの中で再現した．

rebuildしてみるとfailしなくなる．
https://circleci.com/gh/kusumotolab/kGenProg/644

このPRはArgs4Jのヘルプ文字列を修正しただけなので，
別の問題が潜んでそう．
CIでしか起きないのがやばい．
