### ISSUE TITLE
実アプリを試すテストがない

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#339]
Math等の修正にかなり近づいてきたけど，それを試すテストがない．
CI回避のために基本 `@Ignore` しておく．

**Comment by shinsuke-mat** [comment]
作ってみた [KGenProgMainTestForRealBugs.java](
../blob/e75bda588113cb40fb8df2ce8d5853781886a5c9/src/test/java/jp/kusumotolab/kgenprog/KGenProgMainTestForRealBugs.java)

### 問題
`@Ignore` するのはよいけど間違えてIgnore削除したままコミットしそう．
というかした．
[circleciのログ](https://circleci.com/gh/kusumotolab/kGenProg/690?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)（NPEで落ちている理由はCIで `git submodule` してないから）

### 議論
こういう結合テストはJUnitテストにしないほうが良いのかもしれない．
Unitテストの意味がない．
理由はこれら
- 計算コストが高い
- CIで実行するつもりは一切ない（重いので）
- ローカル単体テストで起動されても重すぎて鬱陶しい
- Math02 → 85 → ... と連続で実行するケースもあまりない

### 案
こうする？ベタすぎる気がする．
```java
public class KGenProgMainTestForRealBugs {
  public static void main(String args[]) {
    runMath02();
    // runMath73();
    // runMath85();
  }
```

なにか良い案求む．

**Comment by YoshikiHigo** [comment]
実アプリのバグが直るかテストできるに越したことは無いんですが，実アプリが対象な時点でテストの枠を超えているとも思います．なので，CIのテスト対象はなしでいいですよね．

「案」については，リフレクションを使えばもうちょっとかっこよく書けるように思います．

1. 各バグテストは1つのクラスにする．
```java
class Math85BugTest{
  public static void main(String[] args) {
    // Math85のテスト
  }
}
```

2. バグテストをリフレクションで実行するためのクラス．
```java
class RealBugTestEntryPoint{
  public static void main(String[] args) {
    final String[] realArgs = Arrays.copyOfRange(args, 1, args.length);
    final String className = args[0];
    try {
      final Class<?> main = Class.forName(className);
      final Method method = main.getMethod("main", String[].class);
      method.invoke(null, new Object[] {realArgs});
    } catch (Exception e) {
      // error handling
    }
  }
}
```

3. 実行は，以下のコマンドで．
```
java -jar RealBugTestEntryPoint Math85BugTest (必要であれば引数を書く)
```

この書き方の良い点は，実アプリのバグが増えた場合でも，RealBugTestEntryPointは修正しなくて良いことですね．

**Comment by mtj0928** [comment]
Math に対する Config ファイルを作成する。
テストケースには加えない。

**Comment by mtj0928** [comment]
ref #359
