### ISSUE TITLE
GA周りに埋め込み定数が残っている

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#343]
結合テストの混乱の元．
`Configuration` オブジェクトに頑張って引き上げよう．

```java
//DefaultVariantSelection
  public DefaultVariantSelection() {
    this.maxVariantsPerGeneration = 100;
  }
```

```java
//KGenProgMainTest
    final Mutation mutation = new RandomMutation(10, random, statementSelection);
```

**Comment by mtj0928** [comment]
@mtj0928 が頑張る💪

**Comment by Keigo01** [comment]
- 案1 (不採用)
siblingsCount ->mutatedGenerationCount
crossoverredGenerationCount

- 案2 (採用)
siblingsCount -> mutaionGeneratingCount
crossoverGeneratingCount

**Comment by Keigo01** [comment]
名前と合わせて実装も変更する．
- as is
siblingsCount : mutation によって1つの親から生成される variant の総数
numberOfPair : その世代で crossover によって生成される variant のペアの総数

- to be
mutaionGeneratingCount : その世代で mutation によって生成される variant の総数
crossoverGeneratingCount : その世代で crossover によって生成される variant の総数

fitness の重みで roulette して，mutation の親を決める．
