### ISSUE TITLE
実行時にストラテジーを選択できない

### ISSUE THREAD

**Issue by a-tanikd** [kusumotolab/kGenProg#352]
`FaultLocalization` や `Mutation` などのアルゴリズムを容易に切り替えられるようにストラテジーパターンで実装しているが，実行時にストラテジーを選択する仕組みがない．
現状では，ストラテジーを変更するにはプログラムを書き換える必要がある．

**Comment by mtj0928** [comment]
現状はストラテジーが少ないので、pending
ストラテジーが増えたら、再検討する

**Comment by hnymA** [comment]
ストラテジーが増えたので細分化します．
交叉関連 -> #525 
Fault Localization 関連 -> #526
