### ISSUE TITLE
一時ディレクトリが削除されていない

### ISSUE THREAD

**Issue by Keigo01** [kusumotolab/kGenProg#354]
`Configuration.java` のstaticイニシャライザで作成される一時ディレクトリが実行終了時に削除されていない．
そのため，何度も実行すると `java.io.tmpdir` 以下にごみディレクトリが増えていく．

**Comment by mtj0928** [comment]
- 一時ディレクトリが必要か調べる ( @a-tanikd  )

**Comment by YoshikiHigo** [comment]
いらなさそう．
