### ISSUE TITLE
クラスパスにディレクトリを指定するとビルドに失敗する

### ISSUE THREAD

**Issue by Keigo01** [kusumotolab/kGenProg#357]
タイトルの通り．
クラスパスにディレクトリを指定した場合，`TargetProject` にはそのディレクトリに含まれるすべてのクラスファイルがクラスパスとして登録されている．
しかし，クラスパスとしてクラスファイルを直接指定すると，コンパイルの際にクラスファイルのパッケージが分からないためビルドに失敗する．

**Comment by mtj0928** [comment]
内藤が落ちるテストケースを作る
→そのテストケースを通過できるように柗本先生が修正する
