### ISSUE TITLE
Fitnessを用いたルーレットアルゴリズムの検討

### ISSUE THREAD

**Issue by mtj0928** [kusumotolab/kGenProg#374]
ref #343 
> fitness の重みで roulette して

とあるが，`fitness`の値が0の`Variant`をルーレットの対象にしないのはマズイ気がする．
また，コンパイルに失敗したときは`fitness`の値が`Nan`になってしまうが，その場合はどう扱うか検討したい．

**Comment by shinsuke-mat** [comment]
【議論の結果】
初期状態からテストが全てfailしていた場合にGAを回すかという議論と捉えると良い．
FLが不可能なのでGA回さないほうがよいのでは．

ただし，初期実行で全failの際には適切なメッセージを出すべき．
