### ISSUE TITLE
リリース作業が煩雑

### ISSUE THREAD

**Issue by a3636tako** [kusumotolab/kGenProg#380]
CIによって自動的に作成してほしい

**Comment by h-matsuo** [comment]
`git describe --tags` で以下のような文字列が得られる：

`<直近のタグ名>-<そこからのコミット回数>-<HEAD ID>`

Nightly Build のバージョン番号はこれを採用する。

Java では正式リリース以外のバージョン番号には `-SNAPSHOT` という suffix を付けるのが慣例であるため，正式には以下になる：

`$(git describe --tags)-SNAPSHOT`

具体例：
g741c3c4 に対する Nightly Build のバージョン番号は

`v.0.3-130-g741c3c4-SNAPSHOT`

**Comment by h-matsuo** [comment]
#### どうやってそのコミットで `gradle.properties` がインクリメントされたかを知るのか問題

→ 有馬大先生の案：
そのバージョンのタグで [GitHub Releases](https://github.com/kusumotolab/kGenProg/releases) の URL を叩いて 404 が返ってくるかどうかを見る

めっちゃ簡単。採用

**Comment by h-matsuo** [comment]
```
$ gren changelog --generate --override --data-source=prs --tags=nightly-build
```

上記でいい感じにリリースノート自動生成
