### ISSUE TITLE
PatchesStoreの内部の構造に違和感

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/kGenProg#411]
PatchesStoreは以下のフィールドを持つ．
```java
public class PatchesStore {

  private final List<Patches> patchesList = new ArrayList<>();

  public void add(final Patches patch) {
    patchesList.add(patch);
  }
  ...
```

Patchesは以下のフィールドを持つ．
```java
public class Patches {

  private static Logger log = LoggerFactory.getLogger(Patches.class);

  private final List<Patch> patches = new ArrayList<>();
  ...
```

つまり，``List<List<Patch>>``な構造になってるんだけど，こうしてる特別な理由ってありますか？
もし無いなら，``List<Patch>``にして，名前も``PatchesStore``よりは``PatchStore``の方がよいと思いました．

**Comment by Keigo01** [comment]
`Patch` は1ファイルの変更内容なので，`PatchesStore` を`List<Patch>` にした場合，どの`Patch` がどのバリアントの物か判別がつかないため，そのような構造にしました．

各クラスは以下のものを表しています．
`Patch` : 1ファイルの変更内容．
`Patches` : 1バリアントの変更内容の集合．
`PatchesStore` : 全テストを通過したバリアントの変更内容の集合．

**Comment by YoshikiHigo** [comment]
パッチって言葉はそもそも1コミットの差分を表すものじゃないでたっけ？
1つのバグを修正するために複数のファイルを修正したとしても，生成されるのは1つのパッチ，というのが僕の理解です．

**Comment by shinsuke-mat** [comment]
【2018/11/15 議論】

名前を変える
```
PatchesStore → PatchStore
Pathes       → Patch（1バリアントから生まれる複数ファイルの差分の集合）
Patch        → FileDiff（1ファイルの差分）
```

**Comment by a-tanikd** [comment]
resolved by #422
