### ISSUE TITLE
stopfirstオプションほしい

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#434]
答えを一つ見つけたら即座に終了するオプション．
astorには搭載されている．

実験に便利，かつ実用面でも使えるオプション．

**Comment by a-tanikd** [comment]
`required-solutions = 1` じゃダメなんですか？

**Comment by shinsuke-mat** [comment]
`fitnesss=1`の場合，「個体を発見次第」即座に終了するのがポイントで，
`required-solution=1`だと「その世代の全個体を実行した後」に終了する．

世代ごとに5mかかるような設定の場合，
最悪，正解個体を発見後4m59sで終了する．

**Comment by shinsuke-mat** [comment]
タイムアウトオプションも同じ問題を抱える．
タイムアウト5mで，4m59sで次の世代に入ると最悪6mくらいまで実行される．
