### ISSUE TITLE
バージョン番号の管理方法の改善

### ISSUE THREAD

**Issue by h-matsuo** [kusumotolab/kGenProg#435]
See also #380 .

### 現在の流れ（たぶん）

1. `git tag` でバージョン番号を適当に付ける（手動）
1. `gradle jar` で Jar ファイル作成（手動）
1. Releases に Jar ファイル登録（手動）

### 問題

- バージョン番号の命名規則が揺れる恐れあり
    - すでにタグが `v0.2`, `v.0.3` と不統一になっている
- バージョン番号の不一致が起きる恐れあり
    - 将来 `--version` オプションを実装した場合など，同期させる箇所が増え続ける
    - リリース名では `v0.4` なのに内部では `v0.3` … などが起きかねない

### 議論・提案

CI での自動リリースに合わせて，バージョン管理の方法も改善した方が良いかと思います。
以下の各点について議論・提案したいです。

#### バージョン番号の命名規則を定める

`vX.Y` 形式で良いのか？

#### 手動でバージョン番号を入力する箇所を一つにまとめる

`gradle.properties` 等に `majorVersion` のような値を定義しておいて，バージョンアップ時はそこを上書き → Pull Request でレビュー，という流れでどうでしょうか。

- 単純な `git tag` で行うバージョン付けと異なりレビューが入るため誤操作が起こりにくい
- バージョンアップという作業を 1 つのコミットにできるためログが分かりやすい

`majorVersion` が上書きされたコミットが `master` にマージされれば，CI で自動タグ付け＆自動リリースという流れにすれば良いと思います。

この場合の具体的なバージョンアップ手順は以下になります：

1. `gradle.properties` の `majorVersion` を上書きし，Pull Request
1. レビュー後，`master` にマージ（手動でやるのはここまで）
1. CI がアップデートを検出し，当該コミットにタグ付け＆ビルド
1. CI が Releases ページに Jar ファイルを登録

**Comment by h-matsuo** [comment]
ビルド番号の自動インクリメントまでやり出すと煩雑になるので，番号自体は手動入力で良いと思う

**Comment by shinsuke-mat** [comment]
[2018/11/26 mtg]

### バージョン番号の命名規則
semantic versioning
`v1.2.3 (major, minor, patch)`

### バージョンアップデートの方法
上の通りで．
ミーティングのタイミングで皆でバージョンを上げる．

### メモ
apsec終わったら `v1.0.0` からスタート
