### ISSUE TITLE
git-submoduleが消えとる

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#443]
example/real-bugsが #428 で消えてしまった

**Comment by shinsuke-mat** [comment]
`.gitmodules` ファイルは残っているが，submoduleリファレンスが消えている状態．

加え，`.gitmodules`ファイルからsubmoduleの復元はできないらしい．
これはひどい
https://stackoverflow.com/questions/11258737/restore-git-submodules-from-gitmodules

もう一度 `git-submodule` コマンドを打つ必要がある．
`.gitmodules`ファイルの存在意義が不明．

**Comment by YoshikiHigo** [comment]
あ，すみません，僕ですね...
