### ISSUE TITLE
exp-for-journalにのみ重要なパッチが存在している

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/kGenProg#454]
具体的には，
- JUnitに手を入れている
- ...

**Comment by shinsuke-mat** [comment]
いったん情報をとりまとめ．
備忘録 & 全体像把握のため．

# ■致命的なやつら

### JUnitのannotationタイムアウトでスレッドがkillされない #418
JUnitカスタムで解決．
`junit.framework.TestCase`を改造．
masterにどう取り込むかは要検討．

### JUnitのannotationタイムアウトが継承ベース記法では適用されない #433
JUnitカスタムで解決．
`org.junit.internal.runners.statements.FailOnTimeout` を改造．
masterにどう取り込むかは要検討．

### 無限ループ発生時にKGPが正常に終了しない #392
おそらく #392 と #433 の副作用だとは思う．
よって上記2つを解決すれば自ずと解決するはず．

### classpathの指定周りでバグ #423
クラスローダの適切な利用が必要．

# ■利便性に関わるやつら
### KGPの終了理由が分かりにくい #456
### GAパラメタのデフォルト値が適切でない #404

# ■どうでもよいやつら
### stopfirstオプションほしい #434 
実験中に気づいたISSUE．
まあなくてもよいので無視．

# ■解決済み
### 世代サマリのログ出力タイミングがおかしい#440 
### バリアント数の計算がおかしい #439
### ログ出力でNoSuchElementException #437
### 再利用候補の範囲を絞れない #405
### CUI実行時のオプション指定を上書きできない #391

**Comment by shinsuke-mat** [comment]
上記「致命的なやつら」が全部closeされたので閉じる．
