### ISSUE TITLE
master の内容を取り込まないと CI テストにこけることがある

### ISSUE THREAD

**Issue by h-matsuo** [kusumotolab/kGenProg#463]
### 問題

現状では各ブランチの `HEAD` の内容で `gradle test` しているが，`master` の内容を取り込まないとテストにコケることがある．

#### 案 1

CI でテストを行う際は，毎回 `master` の内容を現在のブランチに一時的にマージしてから行う．

- pros
    - 手作業で行う作業がない
    - 現状の開発フローからの変更がない
- cons 
    - CI 依存のフローになる
    - 村長が疲れる

#### 案 2

開発フローで，各自 最新の `master` の内容を取り込んだ上でプッシュするように定める．
また GitHub で `master` から behind なブランチはマージできないように設定する．

- pros
    - こちらの方が開発フローとしては綺麗
    - `master` にマージされたときの挙動が明らかである
- cons
    - コミット履歴が汚れる（マージコミットだらけになる）

##### 案 3

案 2 かつ `master` へのマージ時は squashed merge にする．
大規模な OSS リポジトリなどで見られるフロー．

- pros
    - コミット履歴も汚れず，開発フローとしても綺麗になる
- cons
    - 1 プルリク 1 コミットとなるため，プルリク内での開発履歴は消える

**Comment by Keigo01** [comment]
結論：
案1 で村長が頑張る．
