### ISSUE TITLE
CIが不安定

### ISSUE THREAD

**Issue by mtj0928** [kusumotolab/kGenProg#490]
CIが失敗する時と成功する時がある
再現性が確保できておらず、原因不明

**Comment by a3636tako** [comment]
ローカルのLinuxでgradle testを実行した際も、たまに発生する（テストが終わらない）ことを確認。

testCloseToZero03で発生したときの状態をデバッガで確認すると、以下のgetTestResults()の中のblockingGetで止まっている
https://github.com/kusumotolab/kGenProg/blob/db8bd3aa6659a196d5224daedaed81d8d739f6d1/src/main/java/jp/kusumotolab/kgenprog/ga/variant/VariantStore.java#L180

Rxのmapの中でblockingGetすると、デッドロックが発生する？

**Comment by a-tanikd** [comment]
恐らく #505 で解決できたはずなので close
