### ISSUE TITLE
javadocの扱いが決まっていない

### ISSUE THREAD

**Issue by mtj0928** [kusumotolab/kGenProg#498]
書くか書かないか，書くならどの程度書くのか，ある程度の方針を決めたいです．
(引数の名前が異なったりする場合，IntelliJのデフォルトだとerror扱いになるので，少なくとも消すか訂正するかしたいです)

**Comment by a-tanikd** [comment]
【2019/01/07 議論結果】
- 書かなくてもいい
- public クラスの public メソッドにつける
- ...
(結論が出ないので pending）

**Comment by hnymA** [comment]
【2019/03/07】
とりあえずjavadocは *執筆する*
自分の担当したクラスについて

厳密なルールは決めずに書いてみて何か問題があればまた考える
