### ISSUE TITLE
Counterクラスの存在意義が謎

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#516]
https://github.com/kusumotolab/kGenProg/blob/884c5d450256de8e06013a314e4f8495ef683d23/src/main/java/jp/kusumotolab/kgenprog/Counter.java#L1-L18

これ必要？

PrimitiveObsession避けたいならAtomicLongで十分だと思う．
concurrentですらないのでLongで十分か．

**Comment by YoshikiHigo** [comment]
僕もいらんと思う．
@ty-v1 くん，どう？

**Comment by ty-v1** [comment]
同感です  
primitive longでもいいと思います
