### ISSUE TITLE
README に記述漏れがある

### ISSUE THREAD

**Issue by a-tanikd** [kusumotolab/kGenProg#544]
[Options](https://github.com/kusumotolab/kGenProg#options) 表に `--config` オプションの説明がない．

**Comment by a3636tako** [comment]
APSECの論文情報を記述する

**Comment by kusumoto-lab** [comment]
JDKのバージョン

**Comment by a-tanikd** [comment]
> JDKのバージョン

具体的に何が足りていないんでしょうか？
ちゃんと把握していないんですが，JDK9以降にも対応しているということですか？

**Comment by ty-v1** [comment]
そうです  
JDK8だけではなく，JDK9・10・11にも対応しているのでそのことをドキュメントに書いたほうがいいと思います。
