### ISSUE TITLE
[CI] 複数の Java バージョンでのマトリックステストをするべき

### ISSUE THREAD

**Issue by h-matsuo** [kusumotolab/kGenProg#545]
#538 で Java 10 / 11 がサポートされた．
サポートしていることを明記するからには，テストも各バージョンで行うべきである．

Java 8 以降の各 JDK と KGP 間のマトリックステストを行う．

**Comment by h-matsuo** [comment]
木曜日のミーティングで決めてもらいたいこと：
- どの JDK でテストを行うか？
    - 個人的には普通に JDK 8, 9, 10, 11 で行えばよいかと思います

**Comment by a3636tako** [comment]
現状1min程度かかる
4倍になるとうっとうしい

いつやるか
+ push時
+ master マージ時
+ リリース時
+ 気が付いたら

master マージ時がよさそう

**Comment by hnymA** [comment]
JDK11以降でマトリックステストを回す
ref #783
