### ISSUE TITLE
crossoverでバリアントが生成できない場合を考慮できていない

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/kGenProg#568]
related to #567 

現状のコードは以下の通り．
https://github.com/kusumotolab/kGenProg/blob/8c0c5081b715a832043e10452990f98698ed4546/src/main/java/jp/kusumotolab/kgenprog/ga/crossover/CrossoverAdaptor.java#L51-L55

これだと，filtedVariantの数が非常に少なかったときにでも，無理矢理にでも交叉しないといけない．

**Comment by h-matsuo** [comment]
1.31 議論

https://github.com/kusumotolab/kGenProg/blob/c3f8c97fb478f6d21550806d5ef73fe8edee0e2e/src/main/java/jp/kusumotolab/kgenprog/ga/crossover/RandomCrossover.java#L35

getSecondVariantSelectionStrategy() は getFirstVariantSelectionStrategy() とは違う Variant を必ず生成するようにすべき．
