### ISSUE TITLE
Fitness が Simple しかない

### ISSUE THREAD

**Issue by h-matsuo** [kusumotolab/kGenProg#569]
現在はテスト通過率のみから Fitness を計算している．
ゴミをたくさん産んだ個体は Fitness を下げるべきである．

個体の持つ Fitness の Immutability を確保しにくい．
実装は要検討．

**Comment by YoshikiHigo** [comment]
- 落ちてたテストが通るようになるとより良いと判断する．
- テストにかかった時間を利用する．
- 個体の大きさ（行数やネスト）を利用する．
