### ISSUE TITLE
VariantSelection で Build Failed が含まれている

### ISSUE THREAD

**Issue by h-matsuo** [kusumotolab/kGenProg#570]
Build Failed が産む個体はたぶん Build Failed するので，排除した方が良いのでは？

**Comment by h-matsuo** [comment]
## 2019.1.31 コメント

Build Failed が含まれることでどの程度パフォーマンスが落ちているのかには興味がある．研究のネタにもなりそう．

また，一般ユーザ向けではない開発用のオプションもあると嬉しい．
今回のような Build Failed を含むか否かもオプション化したいが，オプションが増えすぎるのも問題．

**Comment by h-matsuo** [comment]
この Issue の Reviewer は @mtj0928 とする．

**Comment by YoshikiHigo** [comment]
@RyokoIzuta にアサイン．
