### ISSUE TITLE
実行時にVariant Selectionのストラテジーを選択できない

### ISSUE THREAD

**Issue by hnymA** [kusumotolab/kGenProg#576]
relating to #564 #572 

じじい-oriented 問題を解決した際にVariant Selectionが２つになった．

- DefaultVariantSelection（いわばEliteAndRandomVariantSelection）
- EliteAndOldVariantSelection

オプションを用意していないのでストラテジーを変えるにはプログラムを書き換えないといけない．

## 議論すべきこと
**そもそもオプションいる？**

**Comment by ty-v1** [comment]
## ミーティング
* 起動オプションはいらない
* コードは残す
* 他の選択の戦略を増やすのであれば，起動オプションがあった方が良い  

## 結論
選択の戦略が増えてから考える
