### ISSUE TITLE
可視化ツールの取り込み

### ISSUE THREAD

**Issue by ty-v1** [kusumotolab/kGenProg#577]
## 議論すべきこと
可視化ツールをKGPに取り込むべきか

## KGPに取り込む場合にすべきこと
* KGPへの取り込み方を決める
* READMEの更新

**Comment by ty-v1** [comment]
## ミーティング
### 取り込み案
* KGPのjarにビルド済みのMacawを取り込む(Macawはレポジトリに配置)
* git submoduleに取り込む
* KGPのビルドをするときにビルド済みのMacawをダウンロードする
* MacawへのリンクをREADMEに貼る
* JSON出力時にMacawへリダイレクトするhtmlを生成する
* JSON出力時にjsとcssを外部サーバから取り込むhtmlを生成する
* プラグインを作る

### 懸念点
* 開発者が@ty-v1 のみであるため，更新が難しい
* KGPがMacaw依存するのが気持ち悪い

**Comment by YoshikiHigo** [comment]
MacawリソースのKGPリポジトリへの取り込みはひとまずやらない．
