### ISSUE TITLE
Maven Central Repository に kGenProg を登録する

### ISSUE THREAD

**Issue by mtj0928** [kusumotolab/kGenProg#578]
kGenProg のフレームワークを利用して独自の戦略を作って試す上で，いちいち jar ファイルを用意してパスを通して，とするのはめんどくさい

**Comment by ty-v1** [comment]
## ミーティング
### メリット
* sub moduleを使わないで気軽にKGPの拡張ができる

### 必要なこと
* Maven Central Repositoryの登録には申請が必要

**Comment by mtj0928** [comment]
JitPack を導入したので Close
