### ISSUE TITLE
MavenProjectFactory のマルチブロジェクト対応

### ISSUE THREAD

**Issue by mtj0928** [kusumotolab/kGenProg#581]
Mavenプロジェクトがマルチプロジェクトの時に対応できていない

解決しなければいけない問題は以下の二つ(もっとある？)

## rootpath/pom.xml にあるプロジェクトが末端のプロジェクトの時に親の情報を参照していない
親のpom.xmlの情報を見にいけばいいので，理論上は修正可能．

## rootpath/pom.xml に子プロジェクトがある時の扱い
複数の子プロジェクトを持つことになるので，複数の`TargetProject`が必要になってしまう．
「マルチプロジェクトは対応しない」が楽だけど，UXとしては微妙に悪い．

**Comment by ty-v1** [comment]
## ミーティング
* 先に KGPMain から MavenProjectFactory を呼び出せるようにすべき
* pom から toml を生成できると嬉しい
* ユーザに最低1回ビルドさせる(KGP は pom だけ読む)

**Comment by shinsuke-mat** [comment]
コーナーケースすぎるのでwontfixにして閉じる．
