### ISSUE TITLE
FSに作用するテストの改善

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#618]
現在，テスト実行後にtmpフォルダが残るようになっている．
これ自体は `VariantSerializerTest` の実装の問題で修正は簡単．

本質的な解決として，「ファイルシステムに作用するテスト」の扱いを決めるべき．
FSからの読み込みはともかく書き込む（作用する）テストの場合，
作用の後処理が必須になる．ベタにやるとテストのバグの原因になりがち．

jimfsを使うべき．
https://github.com/google/jimfs

テスト内でメモリ上のFSを作ってそこに書き込む．
後処理は一切いらない．プロセスが終了するとFSも消えるため．

**Comment by shinsuke-mat** [comment]
軽い一時フォルダくらいなら `org.junit.rules.TemporaryFolder` を使うと手軽でよさそう．

```java
  @Rule
  public TemporaryFolder tempFolder = new TemporaryFolder();
```

**Comment by mtj0928** [comment]
ひとまず，`TemporaryFolder`を使う方針でいく
ref #625
