### ISSUE TITLE
TestResult#getExecutedTargetFQNsに実行されていないクラスのFQNが含まれている

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/kGenProg#630]
Math02の失敗テストメソッドは，org.apache.commons.math3.distribution.HypergeometricDistributionTest.testMath1021．
この失敗テストメソッドに対するTestResult#coveragesには862のエントリがあり，対象プロジェクト全てのクラスが含まれていると思われる．
TestResult#getExecutedTargetFQNsの返値（List<FullyQualifiedName>）にも，862個のエントリがあり，実行されていないクラスのFQNが含まれていると思われる．

https://github.com/kusumotolab/kGenProg/blob/9cafd2e0f1630300700bf672ac461596147fb92b/src/main/java/jp/kusumotolab/kgenprog/project/test/TestResult.java#L36-L44
上記のコードを見るに，実行されたクラスのFQNに絞っているという処理は入ってなさそう．
それと，Javadocが「テストのFQN」を取得になっている．

**Comment by mtj0928** [comment]
#638 で解決
