### ISSUE TITLE
LICENSE の内容と現状が乖離している

### ISSUE THREAD

**Issue by ty-v1** [kusumotolab/kGenProg#642]
実際に使用しているライブラリと`LICENSE`に記述してあるライブラリに乖離がある．  

* `LICENSE`に記載してあるが実際に使用しているかわからないライブラリ
  - Apache Commons Lang
* 使っているが`LICENSE`に記述がないライブラリ
  - RxJava
  - Night-Config
* 変更を加えて使用しているライブラリ
  - Junit

**Comment by shinsuke-mat** [comment]
JUnitは改変 & 再配布になるかも

正確には「同梱」だけど，これは「再配布」と見なすべきかもしれない．

**Comment by tt-kuma** [comment]
@ty-v1 のコメントは網羅していないため再調査が必要．
