### ISSUE TITLE
DStarを実装する

### ISSUE THREAD

**Issue by hnymA** [kusumotolab/kGenProg#675]
FL戦略の一つ
![6E21E5C6-4751-48EA-ADCA-FDDCBEA9691A](https://user-images.githubusercontent.com/23432087/67740308-a98a7400-fa58-11e9-8992-224a96d287fb.jpeg)

**Comment by shinsuke-mat** [comment]
Pearson, S., et al. Evaluating and Improving Fault Localization, 
In Proc. International Conference on Software Engineering, pp. 609–620 (2017).

![image](https://user-images.githubusercontent.com/5342911/67748019-5b33a000-fa6d-11e9-863b-cae461b5b73d.png)

**Comment by hnymA** [comment]
depends on #658
