### ISSUE TITLE
使用kGPのバージョンが出力されない

### ISSUE THREAD

**Issue by RyokoIzuta** [kusumotolab/kGenProg#682]
実行時最初に出力されるconfigurationで，動かしたkGPのバージョンが出力されない．
そのため，後から同じ環境で実行をやり直そうとしても，configurationの情報だけでは再現できない．

**Comment by YoshikiHigo** [comment]
なるほど．これは僕が担当します．

**Comment by mtj0928** [comment]
duplicated to #485

**Comment by shinsuke-mat** [comment]
@YoshikiHigo 今作業しています

**Comment by shinsuke-mat** [comment]
ciと連携しないといけないので結構難しいです

**Comment by YoshikiHigo** [comment]
はい，よろしくお願いします．

**Comment by shinsuke-mat** [comment]
#728 で解決済み
