### ISSUE TITLE
結合テストの可読性が低い

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#725]
kGenProgMainTestに気持ち悪い実装が残っている．

```
public void testCloseToZero04() {
    final Path rootPath = Paths.get("example/CloseToZero04");
    final Path productPath = rootPath.resolve(PRODUCT_NAME);
    final Path testPath = rootPath.resolve(TEST_NAME);

    // ↓？？？
    final CandidateSelection selection = new RouletteStatementSelection(new Random(0)); 
    // ↑

    final KGenProgMain kGenProgMain = createMain(rootPath, productPath, testPath, selection);
    final List<Variant> variants = kGenProgMain.run();
    assertThat(variants).hasSize(1).allMatch(Variant::isCompleted);
}
```

このテストでは最低限の設定をした後に，kgpを実行，最低でも一つの修正候補がうまれるかを確認している．
まずい点：
- 結合テストなのに `selection` の生成方法が明示的に指定されている．結合なので内部処理は暗黙的にやるべき．
- しかもその `selection` の引数に新たな乱数オブジェクト `new Random(0);` が生成されている．
kgpでは複数のストラテジ間で一貫して同じ乱数オブジェクトを利用するのに，この結合テストだけその想定を無視したオブジェクト生成をしてしまっている．

**Comment by shinsuke-mat** [comment]
なぜ上記の実装になっているか．
あるテストはあるselectionでないと直せないから．

 - CountDown01 → RouletteStatementAndConditionSelectionで修正可能
 - CloseToZero01 → RouletteStatementで修正可能

問題を言い換えると，上記2つのselectionの修正能力が，包含ではなく排他の関係になってしまっているから．理想としては，完全上位となるselectionストラテジを用意して，それをデフォルトで（暗黙的に）使うというやり方．

簡単ではない．

**Comment by shinsuke-mat** [comment]
結合テストでやり過ぎ，という捉え方もできる．

「あるselectionが期待通りに動いているか」は，結合ではなく単体のレベルで確認するべき．
複数のcandidateの中から期待通りに選択しているかを確認すれば良い．

「あるselectionがAPR全体の効果を上げているか」というテストは結合であってもやり過ぎでは？

であれば，現状の結合テスト6個のどれを最低限KGPが修正を保証する題材かを決めるて，
それ以外を結合テストから排除した方がよさそう．

**Comment by YoshikiHigo** [comment]
現状では，セレクションアルゴリズム（RouletteStatementSelectionやRouletteStatementAndConditionSelection)を，kGenProgの引数や設定ファイルで決めることができない．
v1.6.2ではRouletteStatementAndConditionSelectionを使うようにハードコーディングされている．
とりあえず，設定ファイルにこの項目を追加するのか先な気がする．
