### ISSUE TITLE
CI乗り換え方針が決まっていない

### ISSUE THREAD

**Issue by hnymA** [kusumotolab/kGenProg#731]
cf. #717
GitHub Actionsではスレッド打ち切りテストが不安定なことがわかった
当該テストを無視するか考える際に，CI環境をどうするか考えるべき

1. GHAに乗り換える
1. 両方動かす
1. CircleCIのままにする

**Comment by hnymA** [comment]
現在Circle CIで行っている処理をどこまでGHAで実現できるか調べる必要がある

**Comment by shinsuke-mat** [comment]
see #717

**Comment by hnymA** [comment]
GHAで全て実現できることが分かったのでGHAに乗り換える
