### ISSUE TITLE
入力データに対する異常ケースの処理が不適切

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#734]
related to #645
related to #592

入力データに異常が含まれる場合の処理が不適切であり，
利用者の視点でとても使いにくい．
特にkdemoで致命的．

最初からコンパイルエラーを含む場合
→ パラメタだけ出力されて0世代で終わる（0世代問題）

最初から全テストが通る場合
→ 100万世代に一瞬で到達する（100万世代問題 #645）

**Comment by RyokoIzuta** [comment]
0世代問題，修正見本がかさばるので別issueに立てました（#740）
