### ISSUE TITLE
リファクタリングしたい

### ISSUE THREAD

**Issue by hnymA** [kusumotolab/kGenProg#747]
[SonarLintプラグイン](https://www.sonarlint.org/intellij/)でコードを見ると結構いろいろと指摘されている
簡単なものでいいので改善したい

**Comment by shinsuke-mat** [comment]
[mtg結論]
手動で頑張って直して下さい．
その後にLintをCIに組み込むか議論しよう．

**Comment by shinsuke-mat** [comment]
intellijの標準機能からもかなり文句を指摘されている．
特におれとひご先生が書いた（＝Eclipseで書いた）コード周り．

![image](https://user-images.githubusercontent.com/5342911/84846720-59652e00-b08a-11ea-85bd-7b9efaa6f6b9.png)
![image](https://user-images.githubusercontent.com/5342911/84846741-64b85980-b08a-11ea-805f-6cf80e5b301f.png)

このissueでどこまで対処するかは任せます．
Linter指摘の修正とintellij指摘の修正を別issueに分けても良い．
