### ISSUE TITLE
リリース時のテストがガバい

### ISSUE THREAD

**Issue by hnymA** [kusumotolab/kGenProg#762]
see https://github.com/kusumotolab/kGenProg/pull/760

propertiesの値が明らかにおかしいのにCIのテストに通っている
propertiesの値をチェックするテストがない？

**Comment by ty-v1** [comment]
リリース時にチェック自体はしているみたい
https://github.com/kusumotolab/kGenProg/blob/f33a65ccd23bcac04d83d988da9030b2e543e347/.circleci/check-version.sh#L18-L23

マージ後のジョブは落ちている
https://app.circleci.com/pipelines/github/kusumotolab/kGenProg/1009/workflows/6a49659a-f616-491d-8e28-f4f19d6a5268
