### ISSUE TITLE
What does locate() in JDTASTLocation do?

### ISSUE THREAD

**Issue by goodtaeeun** [kusumotolab/kGenProg#764]
Hello. I am a undergraduate student studying APR in Korea.

I have been interested in APR and was studying your project for better understanding.
I have trouble understanding the mutation part.

To me, the locate() method in JDTASTLocation seems to eventually return it's internal field, "node".

~~~
while (true) {
      final StructuralPropertyDescriptor locationInParent = currentNode.getLocationInParent();
      if (locationInParent == null) {
        break;
      }

      final ASTNode parent = currentNode.getParent();
      int idx = TreePathElement.NOT_LIST;

      if (locationInParent.isChildListProperty()) {
        // Listの場合、indexも覚えておく
        final List<?> children = (List<?>) parent.getStructuralProperty(locationInParent);
        idx = children.indexOf(currentNode);
      }

      treePaths.add(new TreePathElement(locationInParent, idx));

      currentNode = parent;
    }
~~~

In this loop, what is the purpose of getting the locationInParent and the idx, instead of getting the node itself?

~~~
    currentNode = otherASTRoot;
    for (final TreePathElement path : treePaths) {
      currentNode = path.moveToChild(currentNode);
    }

    return currentNode;
~~~

And at here, is the currentNode that is being returned same as the internal field "node"?
If not, what is it?

I've tried to figure it out for days. However I thought it was best to ask you guys directly.

Thank you so much for your awesome project. It really helps a lot.

With all respect,
Kim.

**Comment by YoshikiHigo** [comment]
Dear Kim.

Thank you for using your tool, kGenProg.
Have you found any strange behavior of kGenProg related to the code that you pointed out?
If so, let us provide more information that we replicate the strange behavior.

Best wishes,
Yoshiki

**Comment by goodtaeeun** [comment]
Dear Yoshiki,

Your tool works well and it is beautiful.

However, we were not only using your tool, but also studying your code.
I opened this issue because it was hard to understand the code section I mentioned above.

Regards,
Kim

**Comment by shinsuke-mat** [comment]
Hi Kim,
Thanks for interesting us.

I agree the code looks weird.
Unfortunately, owners of this code has already graduated.

@a3636tako @mtj0928 
Guys, can you explain to him? Or to me? I will translate.

Even worse, we are in hectic situations due to the COVID-19.

Keep this issue open.
I'll get in touch later.

**Comment by goodtaeeun** [comment]
Thank you Shinsuke,

I will be looking forward to it.
I also hope your lab goes through the COVID-19 situation safely.

Regards,
Kim

**Comment by mtj0928** [comment]
Hi @goodtaeeun !

I didn't write the code (the code was written by @a3636tako ), but I can explain it.

At first, please check this PR.
https://github.com/kusumotolab/kGenProg/pull/30/files

You can find out that the `JDTASTLocation` was implemented when some operations were added. 
To mutate an AST of JDT, we have to copy the AST. 

(e.x.)
https://github.com/kusumotolab/kGenProg/blob/0b8852d8854ae379e7a907c650e76b5f17469644/src/main/java/jp/kusumotolab/kgenprog/project/jdt/InsertOperation.java#L40


So, we have to handle two isomorphic ASTs.
To represent a node, we use the path from a root node. 

In this code, kGenProg gets the path to the node which `JDTASTLocation` has.
```Java
		List<TreePathElement> treePaths = new ArrayList<TreePathElement>();
		ASTNode currentNode = node;
		while(true){
			StructuralPropertyDescriptor locationInParent = currentNode.getLocationInParent();
			if(locationInParent == null){
				break;
			}
			
			ASTNode parent = currentNode.getParent();
			int idx = TreePathElement.NOT_LIST;
			
			if(locationInParent.isChildListProperty()){
				//Listの場合、indexも覚えておく
				List<?> children = (List<?>)parent.getStructuralProperty(locationInParent);
				idx = children.indexOf(currentNode);
			}

			treePaths.add(new TreePathElement(locationInParent, idx));
				
			currentNode = parent;
		}
```

And, by using the path, kGenProg identifies the node which is included in the other AST.

```Java
		currentNode = otherASTRoot;
		for(TreePathElement path : treePaths){
			currentNode = path.moveToChild(currentNode);
		}
```


If you have any questions, please feel free to contact us.
Thank you.

(@a3636tako  Please check my reply is correct.)

**Comment by a3636tako** [comment]
Thank you mtj0928 for your reply. It is correct.

The purpose of `locate` method is to find the copied AST's node whose position is the same as the original node.
If the argument of `locate` method is the same AST's root, this method returns the same node as the field.
However, if the argument is a different AST, this method returns a different node, which is a descendant of the argument.

**Comment by goodtaeeun** [comment]
Now I see!!

First of all, thank you so much for all of your replies.

Let me check if I have understood correctly.

First, JDTASTLocation's field "node" does not always reside in the AST of the given "otherASTRoot".
So, in order to locate the equivalent AST node in the AST of the "otherASTRoot", 
we represent the field "node" as a path from it's own root.
Then, we locate the equivalent AST node under the "otherASTRoot" using this path data and return it.

Is this correct?

**Comment by a3636tako** [comment]
Yes, that is perfectly correct!

The `locate` method is used in JDTOperation classes. For example, here: https://github.com/kusumotolab/kGenProg/blob/19ade576e4457c86171431bf1945c1a188cb85a5/src/main/java/jp/kusumotolab/kgenprog/project/jdt/InsertAfterOperation.java#L20
You can see how those JDTOperation classes modify AST of sample code by running their [tests](https://github.com/kusumotolab/kGenProg/blob/master/src/test/java/jp/kusumotolab/kgenprog/project/jdt/InsertAfterOperationTest.java) 
It may be useful in tracing their behavior.

**Comment by goodtaeeun** [comment]
Thank you everyone.

Now I am sure that I understood what ---locate--- method does.

It was a real honor to be replied so sincerely.
I hope your research/project continues to be successful!

By the way, this project is a beauty.
It is so well-implemented and managed.

Best wishes,
Kim.
