### ISSUE TITLE
マニュアルを見ているだけでは設定名が分からないオプションがある

### ISSUE THREAD

**Issue by RyokoIzuta** [kusumotolab/kGenProg#766]
Configurationで出力されているオプションのうち，
READMEとdoc/kgenprog.tomlに説明がないものがあります．
設定の仕方が分からないので追加したいです．
私が見つけたのは `no-output` （ `needNotOutput` が切り替わる）だけですが，他にもあるかもしれません．

**Comment by hnymA** [comment]
READMEにも全てのオプションについて説明を書くべき
「利用者はこのオプション使わなさそう」とか考えないで全部書く
