### ISSUE TITLE
JDTASTLocation#locate が変異でも正しく動作しない

### ISSUE THREAD

**Issue by hrtwt** [kusumotolab/kGenProg#791]
related to #755

#755 では，`JDTASTLocation#locate` は変異では正しく動作するとされていたが，変異でも，`InsertBeforeOperation` などの AST の構造を変更する操作を行うと，続く `locate`  が正しく動作しない．

**Comment by shinsuke-mat** [comment]
- locateではlocate対象の2つの木が同形という前提をおいている
- 同形ではない木のlocateに失敗する．
- 実際には同形ではない木をlocateするケースが存在する．
- ケース1：crossover．これは自明．今までの話．#790 #755
- ケース2：deleteなどの「astノードの前側」に作用する操作適用後のmutation．

#755 での丸山先生の指摘はおそらく後者．
木の前側を変更してしまうと，「木のルートのみ」で探索するlocateだとずれが発生する．
「木のルート＋木の中身」の2つを頼りにlocateしないといけない．
