### ISSUE TITLE
一部の Windows10 環境で PatchSerializerTest に失敗する

### ISSUE THREAD

**Issue by hrtwt** [kusumotolab/kGenProg#797]
## 起こっていること

[CI](https://github.com/kusumotolab/kGenProg/runs/1201748359
) と @hrtwt の使用しているPC3台の win10 環境で `PatchSerializerTest#testPatch` に失敗する．
@hrtwt の環境では master(v1.7.4) でも失敗する．

## 失敗のフロー （手元で調べた，CIはどうなってるか不明）

* [`ASTRewrite#rewriteAST`](https://www.ibm.com/support/knowledgecenter/sk/SS5JSH_9.5.0/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/dom/rewrite/ASTRewrite.html#rewriteAST-org.eclipse.jface.text.IDocument-java.util.Map-) が `IllegalArgumentException` を投げる．
https://github.com/kusumotolab/kGenProg/blob/7871b21e7cc4e6408b34d048393f7aff53b45ae2/src/main/java/jp/kusumotolab/kgenprog/project/jdt/JDTOperation.java#L54

* `JDTOperation#apply` が例外を `NullObject` である `createGenerationFailedSourceCode` に変換．
https://github.com/kusumotolab/kGenProg/blob/7871b21e7cc4e6408b34d048393f7aff53b45ae2/src/main/java/jp/kusumotolab/kgenprog/project/jdt/JDTOperation.java#L33-L36

* 100行目で予期していない `NullObject` が返ってくるため，110行目のアサーションに引っかかる．
https://github.com/kusumotolab/kGenProg/blob/7b1d7552ba2138c8b25a3840c1e821b43f97241a/src/test/java/jp/kusumotolab/kgenprog/output/PatchSerializerTest.java#L100
https://github.com/kusumotolab/kGenProg/blob/7b1d7552ba2138c8b25a3840c1e821b43f97241a/src/test/java/jp/kusumotolab/kgenprog/output/PatchSerializerTest.java#L110

## 試したこと

* `example/CloseToZero01/src/example/CloseToZero.java` に含まれる日本語をすべて削除するとテストに成功する．
https://github.com/kusumotolab/kGenProg/blob/32f06b8e23f126e763887fe95968a85b21e9f55d/example/CloseToZero01/src/example/CloseToZero.java#L5-L16

* 上の状態で，下の `//bug here`  を `//バグヒアー` に変更するとテストに失敗する．
https://github.com/kusumotolab/kGenProg/blob/32f06b8e23f126e763887fe95968a85b21e9f55d/example/CloseToZero01/src/example/CloseToZero.java#L19

* `v1.7.2` ではテストに成功し， `v1.7.3` では失敗する．

**Comment by tt-kuma** [comment]
intellijからテスト実行したら成功したが，`gradle test`でテストしたら失敗した．

**Comment by ty-v1** [comment]
## 自分の環境での調査
- intellij + junitで実行 -> 落ちない
- intellij + gradleで実行 -> 落ちる

### エンコーディングの確認
- intellij + junitで実行: UTF-8 
![a](https://user-images.githubusercontent.com/23548312/96254916-0b891400-0ff1-11eb-882e-5f2fff092a5f.png)

- intellij + gradleで実行: windows31-j(shift-jis)
![a](https://user-images.githubusercontent.com/23548312/96255408-d4673280-0ff1-11eb-8330-49234a7f9d97.png) 

windows環境によってテスト結果が異なるのは，テストの実行方法が異なるのが原因でよさそう

**Comment by ty-v1** [comment]
下のコードのメソッドの最後に`a++`を挿入する時を考える．　　
```java
public class Sample {

  /**
   * Java学習用のサンプル
   * 変数宣言と単項演算子のサンプルである
   */
  method() {
    int a = 0;
  }
}
```

windows環境で実行すると，JDTは上のコードをwindows-31jとして読み込みASTを作る．
```java
public class Sample {

  /**
   * Java蟄ｦ鄙堤畑縺ｮ繧ｵ繝ｳ繝励Ν
   * 螟画焚螳｣險?縺ｨ蜊倬??ｼ皮ｮ怜ｭ舌?繧ｵ繝ｳ繝励Ν縺ｧ縺ゅｋ
   */
  method() {
    int a = 0;
  }
}
```

windows-31jとして読み込んだコードから生成されるAST
![image](https://user-images.githubusercontent.com/23548312/97148800-11c87e80-17af-11eb-88b7-3f34ce637287.png)

このASTに`a++`を挿入すると以下のASTができる．
![image](https://user-images.githubusercontent.com/23548312/97148887-31f83d80-17af-11eb-92ce-d435c30e49b8.png)

```java
public class Sample {

  /**
   * Java蟄ｦ鄙堤畑縺ｮ繧ｵ繝ｳ繝励Ν
   * 螟画焚螳｣險?縺ｨ蜊倬??ｼ皮ｮ怜ｭ舌?繧ｵ繝ｳ繝励Ν縺ｧ縺ゅｋ
   */
  method() {
    int a = 0;
	a++;
  }
}
```

一方で，UTF-8として読み込んだコードから以下のASTが生成される．
![image](https://user-images.githubusercontent.com/23548312/97149673-6caea580-17b0-11eb-8bbe-dc11b0c391c4.png)

UTF-8として読み込んだコードは109文字であるため，このASTに対して操作を適用，つまり126文字目に`a++`を挿入することはできない．そのため，`MalformedTreeException`が発生する．
