### ISSUE TITLE
解パッチがファイル出力offでログにも表示されなくなる & ファイル出力オプションの挙動が不自然

### ISSUE THREAD

**Issue by ty-v1** [kusumotolab/kGenProg#801]
`noNeedOutput` を`false`に設定すると，修正パッチをファイルにも標準出力にも出力しない．

https://github.com/kusumotolab/kGenProg/blob/master/src/main/java/jp/kusumotolab/kgenprog/output/Exporters.java#L28-L36

**Comment by shinsuke-mat** [comment]
現状はこう．
noNeedOutput = 0 でコンソールにすらパッチが出力されなくなる．

| noNeedOutput | historyRecord | where to output? |
| --           | --            | --               |
| 0            | 0             | consl+file       |
| 1            | 0             |                  |
| 0            | 1             | consl+file+json  |
| 1            | 1             | json             |


コンソール出力は常に必要なはず．
こうあるべき．

| noNeedOutput | historyRecord | where to output? |
| --           | --            | --               |
| 0            | 0             | consl+file       |
| 1            | 0             | consl            |
| 0            | 1             | consl+file+json  |
| 1            | 1             | consl+json       |


noNeedOutput と historyRecord は前者のみが非定型なので解釈しにくい．
より改善するとこう．両方非定型にする．

| noPatchOutput | noHistoryRecord | where to output? |
| --            | --              | --               |
| 0             | 0               | consl+file+json  |
| 1             | 0               | consl+file       |
| 0             | 1               | consl+json       |
| 1             | 1               | consl            |

デフォルトは noPatchOutput = 1, noHistoryRecord = 1 でよさそう

**Comment by shinsuke-mat** [comment]
両方肯定系の方がより自然か．
コードも読みやすいし．

| patchOutput | historyRecord | where to output? |
| --            | --              | --               |
| 0             | 0               | consl            |
| 1             | 0               | consl+json       |
| 0             | 1               | consl+file       |
| 1             | 1               | consl+file+json  |

**Comment by RyokoIzuta** [comment]
patchOutputがfileの出力を管理していて，historyRecordがjsonの管理をしているのであっていますか？
両方否定形にする前後でwhere to output内の内容が入れ替わっているので

**Comment by shinsuke-mat** [comment]
> patchOutputがfileの出力を管理していて，historyRecordがjsonの管理をしているのであっていますか？
厳密には
- patchoutput → パッチdiffのファイル出力
- historyRecord → 歴史jsonのファイル出力

> 内容が入れ替わっているので
just a typo
直しといた
