### ISSUE TITLE
EmptyBuildResultsがemptyじゃない

### ISSUE THREAD

**Issue by RyokoIzuta** [kusumotolab/kGenProg#823]
[ProjectBuilder.java](https://github.com/kusumotolab/kGenProg/blob/master/src/main/java/jp/kusumotolab/kgenprog/project/build/ProjectBuilder.java)でEmptyBuildResultsを生成する時，次のようになっている
```
return new EmptyBuildResults(diagnostics, progress.toString());
```

emptyだと言いながら値を渡している．

**Comment by YoshikiHigo** [comment]
これってEmptyBuildResultsという名前が悪いという方向からの修正でもOK?
例えば，FailedBuildResultsという名前であれば，ビルドの失敗情報を渡すのは違和感ないよね．

**Comment by RyokoIzuta** [comment]
はい，名前を修正する方向でいいと思います

**Comment by YoshikiHigo** [comment]
PR投げました．
@RyokoIzuta さんをレビューワーにしたので，レビューお願いします．
