### ISSUE TITLE
CONTRIBUTING.mdがGitHubに認識されてない

### ISSUE THREAD

**Issue by hrtwt** [kusumotolab/kGenProg#828]
## 何が起こっているか

[Community profile](https://github.com/kusumotolab/kGenProg/community) では `CONTRIBUTING.md` が存在しないことになっている．
実際には `kGenProg/doc/CONTRIBUTING.md` に存在するので，GitHubに認識させたい．

![image](https://user-images.githubusercontent.com/29752757/102591618-a9b26b00-4155-11eb-9aad-0b69d8fd616a.png)

## 解決策
[Setting guidelines for repository contributors](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors) によると

*  `repository's root`
* `docs`
* `.github`

のいずれかに置けばいい．

**Comment by hnymA** [comment]
`docs` にする

**Comment by hrtwt** [comment]
認識されたのでclose
