### ISSUE TITLE
コレクションを持つデータオブジェクトの再検討

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#90]
```java
public class GeneratedSourceCode {
  private List<GeneratedAST> files;
```
何も考えずに集合の保持にListインタフェースを使いすぎ．
適切なCollectionインタフェースと実装を選ぶべき．

検討事項
- 要素の順序の保証
- 要素の重複の扱い
- 要素のImmutability

**Comment by YoshikiHigo** [comment]
基本的にCollectionをreturnを返すのは避ける．
理由がなければListを使う方針．
